# Generated by Django 4.2.4 on 2023-10-25 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardProcessAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128, unique=True, verbose_name='действие')),
                ('description', models.CharField(max_length=512, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'стандартное действие по проверке процесса',
                'verbose_name_plural': 'стандартные действия по проверке процесса',
            },
        ),
        migrations.CreateModel(
            name='StandardProductAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128, unique=True, verbose_name='действие')),
                ('description', models.CharField(max_length=512, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'стандартное действие по проверке продукта',
                'verbose_name_plural': 'стандартные действия по проверке продукта',
            },
        ),
        migrations.CreateModel(
            name='StandardSampleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128, unique=True, verbose_name='действие')),
                ('description', models.CharField(max_length=512, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'стандартное действие по отправке образца',
                'verbose_name_plural': 'стандартные действия по проверке образцов',
            },
        ),
        migrations.CreateModel(
            name='StandardActionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(help_text='сортировка действий по возрастанию', verbose_name='приоритет действия')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_matrix', to='quality.standarddefect', verbose_name='дефект')),
                ('process_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_matrix', to='actioncards.standardprocessaction', verbose_name='действие по проверке процесса')),
                ('product_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_matrix', to='actioncards.standardproductaction', verbose_name='действие по проверке продукта')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_matrix', to='products.productcategory', verbose_name='категория продукта')),
                ('sample_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_matrix', to='actioncards.standardsampleaction', verbose_name='действие по отправки образа')),
            ],
            options={
                'verbose_name': 'матрица действий',
                'verbose_name_plural': 'матрица действий',
            },
        ),
        migrations.AddConstraint(
            model_name='standardactionmatrix',
            constraint=models.UniqueConstraint(fields=('product_category', 'defect', 'process_action'), name='unique_process_action_for_defect_and_category'),
        ),
        migrations.AddConstraint(
            model_name='standardactionmatrix',
            constraint=models.UniqueConstraint(fields=('product_category', 'defect', 'product_action'), name='unique_product_action_for_defect_and_category'),
        ),
        migrations.AddConstraint(
            model_name='standardactionmatrix',
            constraint=models.UniqueConstraint(fields=('product_category', 'defect', 'sample_action'), name='unique_sample_action_for_defect_and_category'),
        ),
        migrations.AddConstraint(
            model_name='standardactionmatrix',
            constraint=models.UniqueConstraint(fields=('product_category', 'defect', 'priority'), name='unique_priority_for_defect_and_category'),
        ),
    ]
