# Generated by Django 4.2.4 on 2023-10-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actioncards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardprocessaction',
            name='task',
            field=models.CharField(max_length=128, unique=True, verbose_name='задача'),
        ),
        migrations.AlterField(
            model_name='standardproductaction',
            name='task',
            field=models.CharField(max_length=128, unique=True, verbose_name='задача'),
        ),
        migrations.AlterField(
            model_name='standardsampleaction',
            name='task',
            field=models.CharField(max_length=128, unique=True, verbose_name='задача'),
        ),
    ]
