# Generated by Django 4.2.4 on 2023-10-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название дефекта')),
                ('description', models.CharField(max_length=512, verbose_name='описание дефекта')),
                ('image', models.ImageField(upload_to='images/defects/', verbose_name='фото дефекта')),
            ],
            options={
                'verbose_name': ('дефект',),
                'verbose_name_plural': 'дефекты',
            },
        ),
    ]
