# Generated by Django 4.2.4 on 2023-10-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название дефекта')),
                ('description', models.CharField(max_length=512, verbose_name='описание дефекта')),
                ('image', models.ImageField(blank=True, null=True, unique=True, upload_to='images/defects/', verbose_name='фото дефекта')),
            ],
            options={
                'verbose_name': 'стандартый дефект',
                'verbose_name_plural': 'стандартные дефекты',
            },
        ),
        migrations.DeleteModel(
            name='Defect',
        ),
    ]
