# Generated by Django 4.2.4 on 2023-10-25 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='название')),
                ('description', models.CharField(max_length=128, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория продукта',
                'verbose_name_plural': 'категории продуктов',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код продукта')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Наименование')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='категория продукта')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='specification', serialize=False, to='products.product', verbose_name='продукт')),
                ('acid_meq', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.acidmeq', verbose_name='Эквивалентная масса кислоты')),
                ('adhesion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.adhesion', verbose_name='Адгезия')),
                ('base_meq', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.basemeq', verbose_name='Эквивалентная масса основания')),
                ('conductivity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.conductivity', verbose_name='Электропроводность')),
                ('density', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.density', verbose_name='плотность')),
                ('gloss', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.gloss', verbose_name='Блеск')),
                ('hegman_fineness', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.hegmanfineness', verbose_name='Степень перетира по Хегману')),
                ('hiding_power', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.hidingpower', verbose_name='Укрывистость')),
                ('ph', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.ph', verbose_name='ph')),
                ('resistivity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.resistivity', verbose_name='Удельное сопротивление')),
                ('roughness', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.roughness', verbose_name='Шероховатость')),
                ('solid_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.solidcontent', verbose_name='сухой остаток')),
                ('solvent_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.solventcontent', verbose_name='Содержание сольвентов')),
                ('thickness', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.thickness', verbose_name='Толщина покрытия')),
                ('viscosity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_spec', to='specifications.viscosity', verbose_name='Вязкость')),
            ],
            options={
                'verbose_name': 'спецификация продукта',
                'verbose_name_plural': 'спецификации продуктов',
            },
        ),
    ]
