# Generated by Django 4.2.4 on 2023-10-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='product_specification', serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'спецификация продукта',
                'verbose_name_plural': 'спецификации продуктов',
            },
        ),
    ]
