# Generated by Django 4.2.4 on 2023-10-24 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='название')),
                ('description', models.CharField(max_length=128, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория продукта',
                'verbose_name_plural': 'категории продуктов',
            },
        ),
        
    ]
