# Generated by Django 4.2.4 on 2023-10-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0002_alter_gloss_options_alter_ph_options'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='acid_meq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.acidmeq', verbose_name='Эквивалентная масса кислоты'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='adhesion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.adhesion', verbose_name='Адгезия'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='base_meq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.basemeq', verbose_name='Эквивалентная масса основания'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='conductivity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.conductivity', verbose_name='Электропроводность'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='density',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.density', verbose_name='плотность'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='gloss',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.gloss', verbose_name='Блеск'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='hegman_fineness',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.hegmanfineness', verbose_name='Степень перетира по Хегману'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='hiding_power',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.hidingpower', verbose_name='Укрывистость'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='ph',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.ph', verbose_name='ph'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='resistivity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.resistivity', verbose_name='Удельное сопротивление'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='roughness',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.roughness', verbose_name='Шероховатость'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='solid_content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.solidcontent', verbose_name='сухой остаток'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='solvent_content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.solventcontent', verbose_name='Содержание сольвентов'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='thickness',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.thickness', verbose_name='Толщина покрытия'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='viscosity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specification', to='specifications.viscosity', verbose_name='Вязкость'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='specification', serialize=False, to='products.product'),
        ),
    ]
