# Generated by Django 4.2.4 on 2023-10-24 08:13

from django.db import migrations, models
import django.db.models.deletion

from products.models import ProductCategory


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='категория продукта'),
            preserve_default=False,
        ),
    ]
