version: "3.8"

services:
  database:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    networks:
      - my_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - database

  backend:
    build:
      context: ../backend
      target: dev
    restart: always
    volumes:
      - ../backend:/app/:ro
    env_file:
      - .env.development
    ports:
      - "8000:8000"
    networks:
      - my_network
    depends_on:
      - database
  
  frontend:
    build:
      context: ../frontend
      target: dev
    volumes:
      - ../frontend/src:/app/src:ro
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  my_network: