# Generated by Django 4.2.4 on 2023-10-26 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualityproblems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containment',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='countermeasure',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='extraaction',
            name='action_type',
            field=models.CharField(choices=[('PRODUCT', 'Продукт'), ('PROCESS', 'Процесс'), ('PEOPLE', 'Люди'), ('METHOD', 'Метод')], max_length=16, verbose_name='Категория действия'),
        ),
        migrations.AlterField(
            model_name='extraaction',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='extraaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_extra_actions', to=settings.AUTH_USER_MODEL, verbose_name='добавил'),
        ),
        migrations.AlterField(
            model_name='extrasampleaction',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='extrasampleaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_extra_samples', to=settings.AUTH_USER_MODEL, verbose_name='добавил'),
        ),
        migrations.AlterField(
            model_name='processaction',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='productaction',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='sampleaction',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='sampleaction',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_actions', to='qualityproblems.lineproblem', verbose_name='проблема'),
        ),
    ]
