# Generated by Django 4.2.4 on 2023-10-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityproblems', '0002_alter_containment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineproblem',
            name='status',
            field=models.CharField(blank=True, choices=[('FILL', 'Сбор данных'), ('INVESTIGATE', 'Расследование'), ('COUNTERMEASURE', 'Внедрение контрмер'), ('CHECK', 'Отслеживание результата'), ('CLOSED', 'Закрыт')], default='FILL', max_length=16, verbose_name='статус'),
        ),
    ]
