# Generated by Django 4.2.4 on 2023-10-28 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualityproblems', '0004_remove_lineproblem_problem_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='extrasampleaction',
            name='created_by',
        ),
        migrations.AddField(
            model_name='extraaction',
            name='requested_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='requested_actions', to=settings.AUTH_USER_MODEL, verbose_name='запросил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrasampleaction',
            name='requested_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='requested_samples', to=settings.AUTH_USER_MODEL, verbose_name='запросил'),
            preserve_default=False,
        ),
    ]
