# Generated by Django 4.2.4 on 2023-10-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gloss',
            options={'verbose_name': 'Блеск', 'verbose_name_plural': 'Блеск'},
        ),
        migrations.AlterModelOptions(
            name='ph',
            options={'verbose_name': 'ph', 'verbose_name_plural': 'ph'},
        ),
    ]
