# Generated by Django 4.2.4 on 2023-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Пользователь'), ('ADMIN', 'Администратор')], default='USER', max_length=16, verbose_name='Роль'),
        ),
    ]
