# Generated by Django 4.2.4 on 2023-09-11 09:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[users.models.phone_validator], verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, height_field=100, upload_to=users.models.profile_photo, verbose_name='Фото пользователя', width_field=100),
        ),
    ]
