# Generated by Django 4.2.4 on 2023-09-11 10:36

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_middle_name_user_phone_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[users.models.phone_is_digit, django.core.validators.MinLengthValidator(10, 'В номере телефона должно быть не менее 10-ти цифр')], verbose_name='Телефон'),
        ),
    ]
