# Generated by Django 4.2.4 on 2023-09-11 10:40

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[users.models.phone_validator, django.core.validators.MinLengthValidator(limit_value=10, message='В номере телефона должно быть не менее 10-ти цифр')], verbose_name='Телефон'),
        ),
    ]
