# Generated by Django 4.2.4 on 2023-09-21 18:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=18, validators=[users.models.phone_validator], verbose_name='телефон'),
        ),
    ]
