name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: |
            docker compose stop
            docker compose rm -f backend
            docker compose rm -f frontend
            docker image prune -fa
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} > .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env
            echo DEBUG=${{ secrets.DEBUG }} >> .env
            echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
            echo ALLOWED_HOSTS="${{ secrets.ALLOWED_HOSTS }}" >> .env
            echo CSRF_TRUSTED_ORIGINS="${{ secrets.CSRF_TRUSTED_ORIGINS }}" >> .env
            echo CORS_ALLOWED_ORIGINS="${{ secrets.CORS_ALLOWED_ORIGINS }}" >> .env
            echo ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}" >> .env
            echo ADMIN_FIRST_NAME="${{ secrets.ADMIN_FIRST_NAME }}" >> .env
            echo ADMIN_LAST_NAME="${{ secrets.ADMIN_LAST_NAME }}" >> .env
            echo ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}" >> .env
            source .env
            docker compose down
            docker compose up -d