name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_backend:
    name: Backend flake8 and pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.6
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        python -m pip install pytest-django faker
    - name: Run flake8 test
      run: python -m flake8
    - name: Run pytest
      run: python -m pytest -p no:warnings
  
  test_frontend:
    name: Run frontend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up node version
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install project
      run: npm ci
    - name: Run tests
      run: npm test a
